### ISSUE TITLE
Correct reverse proxy setup?

### ISSUE THREAD

**Issue by IngwiePhoenix** [elsirion/clnurl#12]
Hello!

It seems that an Alby user can not zap my comments on Nostr and it might be related to how I configured my lnurl.

So, since I use Caddy, and not NGINX nor nix, I wanted to confirm if I am doing everything right :)

First, for context: https://primal.net/e/note1479fjs9z5wtrfm84pjc3pv79nqnw736xkl3964q8570d0mvgg4jqtgvq3q

Now then:

I use two servers; a VPS acting as a gateway and a homeserver behind a daily changing IP. Both are linked via a Headscale VPN through which they send requests and responses. Many of my services are run from home through this setup.

On my server, I use this block:

```caddy
birb.it {
  handle /.well-known/lnurlp/ingwie {
    redir https://zaps.birb.it/lnurl
  }
  handle /.well-known/* {
    uri strip_prefix /.well-known
    header Access-Control-Allow-Origin *
    file_server {
      root /srv/birb.it/well-known
    }
  }
  handle {
    reverse_proxy localhost:8080
  }
}
```

This handles my lnurl, my Nostr NIP-5 and another service.

The `zaps.birb.it` address is proxied from the server, to the homeserver, where the corresponding config is simply this:

```caddy
zaps.birb.it {
  reverse_proxy localhost:9876
}
```

This points directly to my clnurl configuration:

```
plugin=/usb/opt/clnurl/target/release/clnurl
clnurl_base_address=https://zaps.birb.it
clnurl_listen=0.0.0.0:9876
clnurl_description=Give the bird a burger!
clnurl_nostr_pubkey=<...>
```

Is there something I missed?

Oh, I should note: Caddy always passes `x-forwarded-for` and `host` headers to upstream.

Thanks, and kind regards!

**Comment by elsirion** [comment]
My best guess: `redir https://zaps.birb.it/lnurl` doesn't work for some implementations because they don't follow redirects. I'd just reverse proxy to be safe. Also, don't forget to add `header Access-Control-Allow-Origin *` so that browsers don't block cross-site requests.

**Comment by elsirion** [comment]
Also, if you want real Zaps that show up for others you need another plugin: https://github.com/thesimplekid/cln-zapper-rs

EDIT: There's also a guide on setup apparently: https://github.com/TheFockinFury/Non-Custodial-Nostr-Zaps-CLN

**Comment by IngwiePhoenix** [comment]
Thanks! I added the relevant header. Forgot about that one.

It was also pointed out to me, that there are some additional keys in the returned JSON from Alby compared to this plugin.

Look at the differences here:

```
curl "https://birb.it/.well-known/lnurlp/ingwie"
# vs.
curl "https://zapaddress.com/.well-known/lnurlp/fc"
```

Maybe the spec for lnurlp was updated? I know it's somewhere in the LUDs repo, but I didn't find it...

**Comment by elsirion** [comment]
Possibly. Can you investigate if you want a fix? While I'm still running it myself I haven't really being paying attention to Nostr because it's too fast-moving for me.

**Comment by elsirion** [comment]
Maybe @thesimplekid is more up to date and can help you out.

**Comment by thesimplekid** [comment]
Just got my node backup the other day I've fallen a bit behind as well. Planning to set up/update the clnurl and zapping plugins this evening. Will take a look as this as well.

**Comment by thesimplekid** [comment]
I was able to get this set up on my end (with nix because that the right way to run a node :wink:). With the only difference from the README being I had to reverse_proxy to `/lnurl` for the ln address. 

So my guess would be its something to do with the redirect, however I was just able to zap you from alby so it is able to get an invoice and send payment, so it seems to be working. I still need to look at the zapper portion. 

> Maybe the spec for lnurlp was updated? I know it's somewhere in the LUDs repo, but I didn't find it...

The lud  is extended by [NIP-57](https://github.com/nostr-protocol/nips/blob/master/57.md)  to include the `allowNostr` and `nostrPubkey` (pubkey of zapper) fields. Looking at the zapaddress and alby response I do see the `commentAllowed` field which seems like a nostr thing, but I don't see it defined in NIPS, LUDS or drafted in alby's fork.

**Comment by elsirion** [comment]
I'll close for now, feel free to re-open if the fix described by @thesimplekid didn't work :)

**Comment by thesimplekid** [comment]
I did find the other fields alby returns and forgot to post back, non of them are nostr specific and shouldn't have any effect on zapping. Though maybe useful to add to this plugin at some point.

**Comment by elsirion** [comment]
I hope we accept additional fields and just ignore them?

**Comment by thesimplekid** [comment]
> I hope we accept additional fields and just ignore them?

We do. I was referring when a request i made for the lnurl struct there are some optional fields we don't return `commentAllowed`  and `payerData` but as they are optional its okay.

CLNurl
```
http "https://zapnuts.xyz/.well-known/lnurlp/thesimplekid"

{
    "allowsNostr": true,
    "callback": "https://zapnuts.xyz/lnurl_api/invoice",
    "maxSendable": 100000000000,
    "metadata": "[[\"text/plain\",\"Gimme money!\"]]",
    "minSendable": 100,
    "nostrPubkey": "620ad52693d3d54f4aee589eaa2c34cf69e6d2dac258e81511ac3cf8f905e303",
    "tag": "payRequest"
}
```
Alby
```
http "https://getalby.com/.well-known/lnurlp/thesimplekid"


{
    "allowsNostr": true,
    "callback": "https://getalby.com/lnurlp/thesimplekid/callback",
    "commentAllowed": 255,
    "maxSendable": 11000000000,
    "metadata": "[[\"text/identifier\",\"thesimplekid@getalby.com\"],[\"text/plain\",\"Sats for thesimplekid\"]]",
    "minSendable": 1000,
    "nostrPubkey": "79f00d3f5a19ec806189fcab03c1be4ff81d18ee4f653c88fac41fe03570f432",
    "payerData": {
        "email": {
            "mandatory": false
        },
        "name": {
            "mandatory": false
        },
        "pubkey": {
            "mandatory": false
        }
    },
    "status": "OK",
    "tag": "payRequest"
}

```

**Comment by IngwiePhoenix** [comment]
Sorry for my very late reply; I was at the hospital and didn't have time to write a proper one. However, the train's wifi was somewhat stable and with the help of `screen` I did poke around my Caddy configuration for quite a while. Sadly, to no avail.

I created a topic at their community: https://caddy.community/t/return-another-response-without-redirecting/20930
And, even after adding the CSP headers, it appears as tho TheGrinder is still getting 400'd: https://primal.net/e/note1p5ge4mt3z0lfk23jgfchgmvy5pdawdmasvvmkxt3r539jlgcwaws6l6q9k

And ontop of all that, my own relay seems to be error'ing out because the DB is too big. Great time...

Anyway; so much for that, I am at my wit's end unfortunately. :/

As for the other fields, I spent some time curl'ing several other addresses and can confirm that Alby seems to be the only one that has so many extra fields. fiatjaf had also once complained about them implementing/introducing things that are technically not in spec; chances are, this is just another one of such cases. Oh well. On the other hand, that means that what this plugin provides should be sufficient! After all, many other people have been able to zap me before just fine; it just seems that TheGrinder can't, for whatever reason. At least he is the only one that said as much.

So yeah; quite confused, for the time being. o.o

**Comment by elsirion** [comment]
*Nevermind, I shouldn't have just skimmed your post, I hope they can help you with `reverse_proxy`*

**Comment by IngwiePhoenix** [comment]
If I do just `reverse_proxy`, then I get 404's, as clnurl does not have a handler for the route `/.well-known/lnurlp/:name`. And, as described in the post to the Caddy community, I tried using `rewrite /lnurl`, which did not work. So I ended up just using redir, which does work (mostly).

The `ingwie2` endpoint is merely my test to figure out the correct way to handle it, since I did not want to break my currently in-use address.

**Comment by thesimplekid** [comment]
> And, even after adding the CSP headers, it appears as tho TheGrinder is still getting 400'd: https://primal.net/e/note1p5ge4mt3z0lfk23jgfchgmvy5pdawdmasvvmkxt3r539jlgcwaws6l6q9k

I am not sure what client or wallet he is using to know for sure, however this error message to me suggests that  it is able to get the lnurl struct from the `/lnurl` path and and the invoice from the callback. If it was an error in one of those calls i would expect an error message something along the lines of can't resolve lnaddress or can't fetch invoice. But without knowing the client that just a guess. 

https://primal.net/e/note1gwtfcs8tke6hpxjz6a7f00crtppqzghgawg0r9p8zr2u7t4z40mqrnrqhk

Since you only have once channel its possible that he is failing to find a route.

If you want you you can give this branch a try you should be able to use `reverse_proxy` without having to rewrite the path as I added an `axum` route for it.

https://github.com/thesimplekid/clnurl/tree/well-known

**Comment by IngwiePhoenix** [comment]
> Since you only have once channel its possible that he is failing to find a route.

Was my thought too - but when he zaps me directly, it worked, which is the odd part.

That said, someone at the Caddy community gave me a hint; and that worked. Probably the most convoluted way possible...but, works.

```
  handle /.well-known/lnurlp/ingwie {
    reverse_proxy * https://100.64.0.2 { # home server's VPN IP
      rewrite /lnurl
      header_up Host zaps.birb.it
      transport http {
        tls_server_name zaps.birb.it # ... which makes this part neccessary. tl;dr: causes TLS issues otherwise.
      }
    }
  }
```

In fact, it's active since a little while now and also got a zap not too long ago too. So it seems to work as expected still. I also poked TheGrinder to see if he can zap me now. If this doesn't work either, I am much more confortable calling it an issue with the software used to initiate the zap. Since he uses Alby, I guess I'll poke them about it to get them involved, maybe they can check on their end what the issue is.

Let's wait and see, maybe it works now, maybe it does not...

I will give the branch a try later anyway; might come in handy!

**Comment by thesimplekid** [comment]
> Since he uses Alby, I guess I'll poke them about it to get them involved, maybe they can check on their end what the issue is.

I've zapped you from using alby using both snort and primal without errors. So its strange its just him.

**Comment by IngwiePhoenix** [comment]
Well, well, well. It looks like the redirect really was the culprit... and Caddy's config for it, is just - excuse my french - totally ass. x.x

![image](https://github.com/elsirion/clnurl/assets/2893716/c4f26fe0-eca4-4e62-a8f3-76e1183fc6ca)

Thank you two for all your input!

I'll definitively change my config to simplify things. 
@thesimplekid please do PR your `well-known` branch, it could come in very handy for configuring reverse proxying. I only know Caddy, and the README only shows snippets of NGINX, but lord knows what people in the world use. x)
