### ISSUE TITLE
clnurl plugin doesn't get cleaned up whtn CLN stops

### ISSUE THREAD

**Issue by niftynei** [elsirion/clnurl#14]
when i start the lightning node up with the plugin, then stop the lightning node, I get the following error when trying to re-start the CLN node. is the clnurl plugin not getting cleaned up on node stop?

```
thread 'main' panicked at 'error binding to 0.0.0.0:9876: error creating server listener: Address already in use (os error 98)', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/hyper-0.14.25/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by niftynei** [comment]
oh wait, maybe this is a me issue? it's under the lightningd process as well?

**Comment by elsirion** [comment]
I don't subscribe to the `stop` even (didn't know it existed back then), I wonder if that's the reasons?

**Comment by elsirion** [comment]
Idk if you have time to test this, but my best guess is that  #15 would solve the issue.

**Comment by laanwj** [comment]
i had the same problem, can confirm that #15 solves the issue for me (looks like cln-zapper-rs needs an analogous change)

**Comment by elsirion** [comment]
Merged then, thx for testing!
